export const words = [
    { value: "Back To The Future", hint: 'Movie'},
    { value: "The Shawshank Redemption", hint: "Movie" },
    { value: "Pulp Fiction", hint: "Movie" },
    { value: "The Godfather", hint: "Movie" },
    { value: "Fight Club", hint: "Movie" },
    { value: "Inception", hint: "Movie" },
    { value: "The Dark Knight", hint: "Movie" },
    { value: "Forrest Gump", hint: "Movie" },
    { value: "The Matrix", hint: "Movie" },
    { value: "Goodfellas", hint: "Movie" },
    { value: "The Lion King", hint: "Movie" },
    { value: "Schindlers List", hint: "Movie" },
    { value: "The Avengers", hint: "Movie" },
    { value: "Back to the Future", hint: "Movie" },
    { value: "Jurassic Park", hint: "Movie" },
    { value: "Interstellar", hint: "Movie" },
    { value: "Gladiator", hint: "Movie" },
    { value: "Braveheart", hint: "Movie" },
    { value: "The Silence of the Lambs", hint: "Movie" },
    { value: "The Sixth Sense", hint: "Movie" },
    { value: "Titanic", hint: "Movie" },
    { value: "The Lord of the Rings The Fellowship of the Ring", hint: "Movie" },
    { value: "Star Wars Episode IV A New Hope", hint: "Movie" },
    { value: "The Breakfast Club", hint: "Movie" },
    { value: "Eternal Sunshine of the Spotless Mind", hint: "Movie" },
    { value: "Inglourious Basterds", hint: "Movie" },
    { value: "The Departed", hint: "Movie" },
    { value: "The Social Network", hint: "Movie" },
    { value: "Casablanca", hint: "Movie" },
    { value: "Gone with the Wind", hint: "Movie" },
    { value: "The Green Mile", hint: "Movie" },
    { value: "The Princess Bride", hint: "Movie" },
    { value: "Shutter Island", hint: "Movie" },
    { value: "The Great Gatsby", hint: "Movie" },
    { value: "The Wizard of Oz", hint: "Movie" },
    { value: "The Godfather Part II", hint: "Movie" },
    { value: "The Dark Knight Rises", hint: "Movie" },
    { value: "Mad Max Fury Road", hint: "Movie" },
    { value: "Blade Runner", hint: "Movie" },
    { value: "The Terminator", hint: "Movie" },
    { value: "Harry Potter and the Philosophers Stone", hint: "Movie" },
    { value: "The Sound of Music", hint: "Movie" },
    { value: "Toy Story", hint: "Movie" },
    { value: "Rocky", hint: "Movie" },
    { value: "The Exorcist", hint: "Movie" },
    { value: "Avatar", hint: "Movie" },
    { value: "Inception", hint: "Movie" },
    { value: "The Pursuit of Happyness", hint: "Movie" },
    { value: "Black Swan", hint: "Movie" },
    { value: "The Grand Budapest Hotel", hint: "Movie" },
    { value: "La La Land", hint: "Movie" },
    { value: "Highway To Hell", hint: 'Song'},
    { value: "Bohemian Rhapsody", hint: "Song"},
    { value: "Imagine", hint: "Song"},
    { value: "Hotel California", hint: "Song"},
    { value: "Shake It Off", hint: "Song"},
    { value: "Hey Jude", hint: "Song"},
    { value: "Thriller", hint: "Song"},
    { value: "Sweet Child o Mine", hint: "Song"},
    { value: "Wonderwall", hint: "Song"},
    { value: "Smells Like Teen Spirit", hint: "Song"},
    { value: "Like a Rolling Stone", hint: "Song"},
    { value: "Uptown Funk", hint: "Song"},
    { value: "Viva la Vida", hint: "Song"},
    { value: "Hallelujah", hint: "Song"},
    { value: "Billie Jean", hint: "Song"},
    { value: "Shape of You", hint: "Song"},
    { value: "Boogie Wonderland", hint: "Song"},
    { value: "Born to Run", hint: "Song"},
    { value: "Sweet Home Alabama", hint: "Song"},
    { value: "Girls Just Want to Have Fun", hint: "Song"},
    { value: "Livin on a Prayer", hint: "Song"},
    { value: "Yesterday", hint: "Song"},
    { value: "I Will Always Love You", hint: "Song"},
    { value: "Stairway to Heaven", hint: "Song"},
    { value: "Dont Stop Believin", hint: "Song"},
    { value: "Imagine Dragons", hint: "Song"},
    { value: "Sweet Caroline", hint: "Song"},
    { value: "Shape of My Heart", hint: "Song"},
    { value: "Wonderful Tonight", hint: "Song"},
    { value: "California Gurls", hint: "Song"},
    { value: "Hit the Road Jack", hint: "Song"},
    { value: "All You Need Is Love", hint: "Song"},
    { value: "Let It Be", hint: "Song"},
    { value: "Hotel Room Service", hint: "Song"},
    { value: "HeartShaped Box", hint: "Song"},
    { value: "Lose Yourself", hint: "Song"},
    { value: "Every Breath You Take", hint: "Song"},
    { value: "I Want to Hold Your Hand", hint: "Song"},
    { value: "Smooth Criminal", hint: "Song"},
    { value: "Piano Man", hint: "Song"},
    { value: "I Will Survive", hint: "Song"},
    { value: "Killing Me Softly with His Song", hint: "Song"},
    { value: "Dont Stop Me Now", hint: "Song"},
    { value: "With or Without You", hint: "Song"},
    { value: "The Sound of Silence", hint: "Song"},
    { value: "Rolling in the Deep", hint: "Song"},
    { value: "Another Brick in the Wall", hint: "Song"},
    { value: "Come Together", hint: "Song"},
    { value: "Sweet Dreams Are Made of This", hint: "Song"},
    { value: "Lets Dance", hint: "Song"},
    { value: "Bridge Over Troubled Water", hint: "Song"},
    { value: "Barbara Streisand", hint: 'Actress'},
    { value: "Meryl Streep", hint: "Actress" },
    { value: "Cate Blanchett", hint: "Actress" },
    { value: "Viola Davis", hint: "Actress" },
    { value: "Charlize Theron", hint: "Actress" },
    { value: "Natalie Portman", hint: "Actress" },
    { value: "Emma Stone", hint: "Actress" },
    { value: "Jennifer Lawrence", hint: "Actress" },
    { value: "Angelina Jolie", hint: "Actress" },
    { value: "Scarlett Johansson", hint: "Actress" },
    { value: "Julia Roberts", hint: "Actress" },
    { value: "Nicole Kidman", hint: "Actress" },
    { value: "Halle Berry", hint: "Actress" },
    { value: "Anne Hathaway", hint: "Actress" },
    { value: "Sandra Bullock", hint: "Actress" },
    { value: "Mila Kunis", hint: "Actress" },
    { value: "Reese Witherspoon", hint: "Actress" },
    { value: "Jennifer Aniston", hint: "Actress" },
    { value: "Kate Winslet", hint: "Actress" },
    { value: "Amy Adams", hint: "Actress" },
    { value: "Maggie Smith", hint: "Actress" },
    { value: "Jessica Chastain", hint: "Actress" },
    { value: "Emily Blunt", hint: "Actress" },
    { value: "Rachel McAdams", hint: "Actress" },
    { value: "Zoe Saldana", hint: "Actress" },
    { value: "Gwyneth Paltrow", hint: "Actress" },
    { value: "Michelle Pfeiffer", hint: "Actress" },
    { value: "Jodie Foster", hint: "Actress" },
    { value: "Emma Watson", hint: "Actress" },
    { value: "Diane Keaton", hint: "Actress" },
    { value: "Amanda Seyfried", hint: "Actress" },
    { value: "Helen Mirren", hint: "Actress" },
    { value: "Julianne Moore", hint: "Actress" },
    { value: "Katherine Hepburn", hint: "Actress" },
    { value: "Mila Jovovich", hint: "Actress" },
    { value: "Drew Barrymore", hint: "Actress" },
    { value: "Sharon Stone", hint: "Actress" },
    { value: "Keira Knightley", hint: "Actress" },
    { value: "Robin Wright", hint: "Actress" },
    { value: "Charlize Theron", hint: "Actress" },
    { value: "Sigourney Weaver", hint: "Actress" },
    { value: "Maggie Gyllenhaal", hint: "Actress" },
    { value: "Greta Gerwig", hint: "Actress" },
    { value: "Zendaya", hint: "Actress" },
    { value: "Judy Garland", hint: "Actress" },
    { value: "Lucille Ball", hint: "Actress" },
    { value: "Sophia Loren", hint: "Actress" },
    { value: "Grace Kelly", hint: "Actress" },
    { value: "Doris Day", hint: "Actress" },
    { value: "Elizabeth Taylor", hint: "Actress" },
    { value: "Audrey Hepburn", hint: "Actress" },
    { value: "Tom Hanks", hint: "Actor" },
    { value: "Leonardo DiCaprio", hint: "Actor" },
    { value: "Denzel Washington", hint: "Actor" },
    { value: "Robert De Niro", hint: "Actor" },
    { value: "Brad Pitt", hint: "Actor" },
    { value: "Johnny Depp", hint: "Actor" },
    { value: "Morgan Freeman", hint: "Actor" },
    { value: "Will Smith", hint: "Actor" },
    { value: "Matt Damon", hint: "Actor" },
    { value: "George Clooney", hint: "Actor" },
    { value: "Tom Cruise", hint: "Actor" },
    { value: "Christian Bale", hint: "Actor" },
    { value: "Samuel L. Jackson", hint: "Actor" },
    { value: "Harrison Ford", hint: "Actor" },
    { value: "Al Pacino", hint: "Actor" },
    { value: "Anthony Hopkins", hint: "Actor" },
    { value: "Sean Connery", hint: "Actor" },
    { value: "Gary Oldman", hint: "Actor" },
    { value: "Daniel Day-Lewis", hint: "Actor" },
    { value: "Russell Crowe", hint: "Actor" },
    { value: "Kevin Spacey", hint: "Actor" },
    { value: "Joaquin Phoenix", hint: "Actor" },
    { value: "Edward Norton", hint: "Actor" },
    { value: "Liam Neeson", hint: "Actor" },
    { value: "Chris Hemsworth", hint: "Actor" },
    { value: "Mark Wahlberg", hint: "Actor" },
    { value: "Idris Elba", hint: "Actor" },
    { value: "Ben Affleck", hint: "Actor" },
    { value: "Michael Fassbender", hint: "Actor" },
    { value: "Hugh Jackman", hint: "Actor" },
    { value: "Robert Downey Jr", hint: "Actor" },
    { value: "Keanu Reeves", hint: "Actor" },
    { value: "Ryan Gosling", hint: "Actor" },
    { value: "Tom Hardy", hint: "Actor" },
    { value: "Chris Evans", hint: "Actor" },
    { value: "Benedict Cumberbatch", hint: "Actor" },
    { value: "Jamie Foxx", hint: "Actor" },
    { value: "Jake Gyllenhaal", hint: "Actor" },
    { value: "Will Ferrell", hint: "Actor" },
    { value: "Owen Wilson", hint: "Actor" },
    { value: "Viggo Mortensen", hint: "Actor" },
    { value: "Dwayne Johnson", hint: "Actor" },
    { value: "Sam Rockwell", hint: "Actor" },
    { value: "Matthew McConaughey", hint: "Actor" },
    { value: "Chadwick Boseman", hint: "Actor" },
    { value: "Steve Carell", hint: "Actor" },
    { value: "Chris Pratt", hint: "Actor" },
    { value: "Daniel Craig", hint: "Actor" },
    { value: "Donald Glover", hint: "Actor" },
    { value: "Timothee Chalamet", hint: "Actor" },
    { value: "Candy Floss", hint: 'Food'},
    { value: "Pizza", hint: "Food"},
    { value: "Sushi", hint: "Food"},
    { value: "Burger", hint: "Food"},
    { value: "Tacos", hint: "Food"},
    { value: "Pasta", hint: "Food"},
    { value: "Salad", hint: "Food"},
    { value: "Steak", hint: "Food"},
    { value: "Curry", hint: "Food"},
    { value: "Chicken Wings", hint: "Food"},
    { value: "Noodles", hint: "Food"},
    { value: "Burrito", hint: "Food"},
    { value: "Cupcake", hint: "Food"},
    { value: "Ice Cream", hint: "Food"},
    { value: "Sushi Roll", hint: "Food"},
    { value: "Popcorn", hint: "Food"},
    { value: "Dumplings", hint: "Food"},
    { value: "Pancakes", hint: "Food"},
    { value: "Cheeseburger", hint: "Food"},
    { value: "Fish and Chips", hint: "Food"},
    { value: "Chocolate Cake", hint: "Food"},
    { value: "Gelato", hint: "Food"},
    { value: "Hot Dog", hint: "Food"},
    { value: "Crispy Fried Chicken", hint: "Food"},
    { value: "Nachos", hint: "Food"},
    { value: "Sushi Sashimi", hint: "Food"},
    { value: "Lasagna", hint: "Food"},
    { value: "Pho", hint: "Food"},
    { value: "Cucumber Salad", hint: "Food"},
    { value: "Beef StirFry", hint: "Food"},
    { value: "Lobster", hint: "Food"},
    { value: "French Fries", hint: "Food"},
    { value: "Fried Rice", hint: "Food"},
    { value: "Caesar Salad", hint: "Food"},
    { value: "Grilled Cheese Sandwich", hint: "Food"},
    { value: "Hamburger", hint: "Food"},
    { value: "Buffalo Wings", hint: "Food"},
    { value: "Tiramisu", hint: "Food"},
    { value: "Cinnamon Roll", hint: "Food"},
    { value: "Peking Duck", hint: "Food"},
    { value: "Ramen", hint: "Food"},
    { value: "Croissant", hint: "Food"},
    { value: "Mushroom Risotto", hint: "Food"},
    { value: "Chicken Parmesan", hint: "Food"},
    { value: "Pad Thai", hint: "Food"},
    { value: "Clam Chowder", hint: "Food"},
    { value: "Tandoori Chicken", hint: "Food"},
    { value: "Mango Sticky Rice", hint: "Food"},
    { value: "Churros", hint: "Food"},
    { value: "Gyoza", hint: "Food"},
    { value: "Baklava", hint: "Food"},
    { value: "Friends", hint: "TV Show" },
    { value: "Friends", hint: "TV Show" },
    { value: "Game of Thrones", hint: "TV Show" },
    { value: "Breaking Bad", hint: "TV Show" },
    { value: "The Office US", hint: "TV Show" },
    { value: "Stranger Things", hint: "TV Show" },
    { value: "The Simpsons", hint: "TV Show" },
    { value: "The Sopranos", hint: "TV Show" },
    { value: "Sherlock", hint: "TV Show" },
    { value: "The Crown", hint: "TV Show" },
    { value: "Black Mirror", hint: "TV Show" },
    { value: "Westworld", hint: "TV Show" },
    { value: "The Mandalorian", hint: "TV Show" },
    { value: "The Walking Dead", hint: "TV Show" },
    { value: "Better Call Saul", hint: "TV Show" },
    { value: "House of Cards", hint: "TV Show" },
    { value: "Chernobyl", hint: "TV Show" },
    { value: "The Big Bang Theory", hint: "TV Show" },
    { value: "Parks and Recreation", hint: "TV Show" },
    { value: "The Haunting of Hill House", hint: "TV Show" },
    { value: "Fargo", hint: "TV Show" },
    { value: "The Handmaids Tale", hint: "TV Show" },
    { value: "Dexter", hint: "TV Show" },
    { value: "Mindhunter", hint: "TV Show" },
    { value: "Rick and Morty", hint: "TV Show" },
    { value: "The Witcher", hint: "TV Show" },
    { value: "The Good Place", hint: "TV Show" },
    { value: "The X-Files", hint: "TV Show" },
    { value: "Twin Peaks", hint: "TV Show" },
    { value: "Narcos", hint: "TV Show" },
    { value: "Money Heist", hint: "TV Show" },
    { value: "The Good Wife", hint: "TV Show" },
    { value: "Orphan Black", hint: "TV Show" },
    { value: "Broadchurch", hint: "TV Show" },
    { value: "Fleabag", hint: "TV Show" },
    { value: "The Boys", hint: "TV Show" },
    { value: "Ozark", hint: "TV Show" },
    { value: "The Umbrella Academy", hint: "TV Show" },
    { value: "The Great British Bake Off", hint: "TV Show" },
    { value: "The Handmaids Tale", hint: "TV Show" },
    { value: "Peaky Blinders", hint: "TV Show" },
    { value: "The Americans", hint: "TV Show" },
    { value: "True Detective", hint: "TV Show" },
    { value: "Succession", hint: "TV Show" },
    { value: "The Leftovers", hint: "TV Show" },
    { value: "Homeland", hint: "TV Show" },
    { value: "The Good Wife", hint: "TV Show" },
    { value: "The Office UK", hint: "TV Show" },
    { value: "BoJack Horseman", hint: "TV Show" },
    { value: "Arrested Development", hint: "TV Show" },    
    { value: "Break a leg", hint: "Phrase" },
    { value: "Bite the bullet", hint: "Phrase" },
    { value: "Hit the hay", hint: "Phrase" },
    { value: "Piece of cake", hint: "Phrase" },
    { value: "Barking up the wrong tree", hint: "Phrase" },
    { value: "Cost an arm and a leg", hint: "Phrase" },
    { value: "Caught between a rock and a hard place", hint: "Phrase" },
    { value: "Cold feet", hint: "Phrase" },
    { value: "Curiosity killed the cat", hint: "Phrase" },
    { value: "Don't cry over spilled milk", hint: "Phrase" },
    { value: "Easy as pie", hint: "Phrase" },
    { value: "Kill two birds with one stone", hint: "Phrase" },
    { value: "Let the cat out of the bag", hint: "Phrase" },
    { value: "On thin ice", hint: "Phrase" },
    { value: "Over the moon", hint: "Phrase" },
    { value: "Pull someone's leg", hint: "Phrase" },
    { value: "Raining cats and dogs", hint: "Phrase" },
    { value: "Rule of thumb", hint: "Phrase" },
    { value: "Saved by the bell", hint: "Phrase" },
    { value: "Spill the beans", hint: "Phrase" },
    { value: "Take it with a grain of salt", hint: "Phrase" },
    { value: "Under the weather", hint: "Phrase" },
    { value: "Whole nine yards", hint: "Phrase" },
    { value: "You can't judge a book by its cover", hint: "Phrase" },
    { value: "An arm and a leg", hint: "Phrase" },
    { value: "A penny for your thoughts", hint: "Phrase" },
    { value: "Actions speak louder than words", hint: "Phrase" },
    { value: "Bite off more than you can chew", hint: "Phrase" },
    { value: "Hit the nail on the head", hint: "Phrase" },
    { value: "Break the ice", hint: "Phrase" },
    { value: "By the skin of your teeth", hint: "Phrase" },
    { value: "Close but no cigar", hint: "Phrase" },
    { value: "Cut to the chase", hint: "Phrase" },
    { value: "Don't put all your eggs in one basket", hint: "Phrase" },
    { value: "Fish out of water", hint: "Phrase" },
    { value: "Give the benefit of the doubt", hint: "Phrase" },
    { value: "In the blink of an eye", hint: "Phrase" },
    { value: "Jump on the bandwagon", hint: "Phrase" },
    { value: "Let sleeping dogs lie", hint: "Phrase" },
    { value: "Miss the boat", hint: "Phrase" },
    { value: "Not playing with a full deck", hint: "Phrase" },
    { value: "Once in a blue moon", hint: "Phrase" },
    { value: "Paint the town red", hint: "Phrase" },
    { value: "Read between the lines", hint: "Phrase" },
    { value: "The ball is in your court", hint: "Phrase" },
    { value: "Through thick and thin", hint: "Phrase" },
    { value: "Up in the air", hint: "Phrase" },
    { value: "When pigs fly", hint: "Phrase" },
    { value: "A dime a dozen", hint: "Phrase" },
    { value: "A picture is worth a thousand words", hint: "Phrase" },
    { value: "All ears", hint: "Phrase" },
    { value: "Bite the dust", hint: "Phrase" },
    { value: "Cast a wide net", hint: "Phrase" },
    { value: "Cry wolf", hint: "Phrase" },
    { value: "Cutting corners", hint: "Phrase" },
    { value: "Drive someone up the wall", hint: "Phrase" },
    { value: "Go down in flames", hint: "Phrase" },
    { value: "Have a whale of a time", hint: "Phrase" },
    { value: "Hit the jackpot", hint: "Phrase" },
    { value: "Jump off the deep end", hint: "Phrase" },
    { value: "Keep your chin up", hint: "Phrase" },
    { value: "Make hay while the sun shines", hint: "Phrase" },
    { value: "No pain, no gain", hint: "Phrase" },
    { value: "On cloud nine", hint: "Phrase" },
    { value: "Put a sock in it", hint: "Phrase" },
    { value: "Steal someone's thunder", hint: "Phrase" },
    { value: "The early bird catches the worm", hint: "Phrase" },
    { value: "Throw in the towel", hint: "Phrase" },
    { value: "Vanishing act", hint: "Phrase" },
    { value: "Wear your heart on your sleeve", hint: "Phrase" },
    { value: "You can't make an omelette without breaking eggs", hint: "Phrase" },
    { value: "A rolling stone gathers no moss", hint: "Phrase" },
    { value: "Back to the drawing board", hint: "Phrase" },
    { value: "Bite your tongue", hint: "Phrase" },
    { value: "Burn the midnight oil", hint: "Phrase" },
    { value: "Cost a pretty penny", hint: "Phrase" },
    { value: "Don't count your chickens before they hatch", hint: "Phrase" },
    { value: "Drop in the bucket", hint: "Phrase" },
    { value: "Face the music", hint: "Phrase" },
    { value: "Get your act together", hint: "Phrase" },
    { value: "Go the extra mile", hint: "Phrase" },
    { value: "Hold your horses", hint: "Phrase" },
    { value: "It takes two to tango", hint: "Phrase" },
    { value: "Jump to conclusions", hint: "Phrase" },
    { value: "Let bygones be bygones", hint: "Phrase" },
    { value: "Make a mountain out of a molehill", hint: "Phrase" },
    { value: "Needle in a haystack", hint: "Phrase" },
    { value: "Out of the frying pan and into the fire", hint: "Phrase" },
    { value: "Play devil's advocate", hint: "Phrase" },
    { value: "Pull yourself together", hint: "Phrase" },
    { value: "Rub salt in the wound", hint: "Phrase" },
    { value: "Speak of the devil", hint: "Phrase" },
    { value: "The straw that broke the camel's back", hint: "Phrase" },
    { value: "Under the rug", hint: "Phrase" },
    { value: "Waste not, want not", hint: "Phrase" },
    { value: "X marks the spot", hint: "Phrase" },
    { value: "You scratch my back, I'll scratch yours", hint: "Phrase" },
    { value: "You've got to go", hint: "Phrase" },
    ]